Update Chameleon pkg Installer (Allow install on ESP). (Credits to Micky1979)

diff --git a/package/Scripts.templates/InstallModule/postinstall b/package/Scripts.templates/InstallModule/postinstall
--- a/package/Scripts.templates/InstallModule/postinstall
+++ b/package/Scripts.templates/InstallModule/postinstall
@@ -2,21 +2,36 @@
 
 set -u
 
-targetVolume="$3"
+configFile='/private/tmp/InstallConfig.plist'
+v_mntptDev=$( /usr/libexec/PlistBuddy -c "Print :ramdisk" ${configFile} | sed -e 's/[[:blank:]]*//g' )
+v_mntpt=$( LC_ALL=C diskutil info ${v_mntptDev} | grep -i 'mount point' | awk '{$1=$2=""; print $0}' \
+                                                                               | sed -e 's/^[ \t]*//' )
 
 moduleName="@moduleName@"
 moduleFile="@moduleFile@"
 logName="@LOG_FILENAME@"
-logFile="${targetVolume}/$logName"
 
 # Check if target volume exists
-if [[ ! -d "$targetVolume" ]]; then
-    echo "$targetVolume volume does not exist!" >&2
-    exit 1
+if [[ ! -d "${v_mntpt}" ]]; then
+    echo "Ram Disk not found volume does not exist!" >&2
+#    exit 1
 fi
 
-exec >>"${logFile}" 2>&1
+mainLine="=============================================================================="
+subLine="------------------------------------------------------------------------------"
 
-[[ -f "${targetVolume}/Extra/modules/$moduleFile" ]] && echo "Module $moduleName installed"
+exec > >(tee -a "${v_mntpt}/${logName}") 2>&1
+
+echo "$mainLine"
+echo "Installing $moduleFile"
+echo "$subLine"
+
+if [[ -f  "${v_mntpt}/Extra/modules/$moduleFile" ]]; then
+    echo "$moduleName installed to Ram disk"
+else
+    echo "*** ERROR:$moduleName not installed"
+fi
+
+echo "$subLine"
 
 exit 0
