Merge Blackosx "pkg features" (r1567). Move GraphicsEnabler into Module (Courtesy of Azimutz sub-Branch). Update all the Localizable.strings files.

diff --git a/package/Scripts/Standard/postinstall b/package/Scripts/Standard/postinstall
--- a/package/Scripts/Standard/postinstall
+++ b/package/Scripts/Standard/postinstall
@@ -1,364 +1,182 @@
 #!/bin/bash
 
-
-diskloader="boot0"
-diskloaderdualboot="boot0md"
-partitionloaderhfs="boot1h"
-partitionloaderfat="boot1f32"
-filesystemloader="boot"
-
-diskmicrocodetype[1]="GRUB,47525542"
-diskmicrocodetype[2]="LILO,4c494c4f"
-
-start ()
-{
-# $1 volume
-
-bootvolume="${@}"
-echo "Volume is $bootvolume"
-bootresources="${0%/*}"
-echo "$bootresources"
-
-if [ -z "${bootvolume}" ]; then
-	echo
-	echo "Cannot find the volume. Exiting."
-	echo
-	exit
-fi
-
-bootdev=$( df "${bootvolume}" | sed -n '2p' | awk '{print $1}' )
-bootrdev=${bootdev/disk/rdisk}
-
-if [ "${bootdev}" = "${bootdev#*disk*s}" ]; then
-	echo
-	echo "ERROR Volume does not use slices."
-	echo
-	exit				
-fi
-
-bootdisk=${bootdev%s*}
-bootrdisk=${bootdisk/disk/rdisk}
-bootslice=${bootdev#*disk*s}
-
 echo "==============================================="
-echo "Installer Variables:"
-echo "********************"
-echo "bootvolume: Volume is ${bootvolume}"
-echo "bootdev: Volume device is ${bootdev}"
-echo "bootrdev: Volume raw device is ${bootrdev}"
-echo "bootslice: Volume slice is ${bootslice}"
-echo "bootdisk: Disk device is ${bootdisk}"
-echo "bootrdisk: Disk raw device is ${bootrdisk}"
-echo "diskloader: Disk loader is ${diskloader}"
-echo "partitionloaderhfs: Partition loader is ${partitionloaderhfs}"
-echo "partitionloaderfat: Partition loader is ${partitionloaderfat}"
-echo "filesystemloader: Filesystem loader is ${filesystemloader}"
-echo "bootresources: Boot Resources is ${bootresources}"
+echo "Main Standard Post-Install Script"
+echo "*********************************"
 echo "-----------------------------------------------"
 echo ""
-echo ""
-}
 
-checkdiskmicrocodetype ()
-{
+# Find location of this script in the package installer
+# so we know where all the other scripts are located.
+
+MYLOCATION="${PWD}/${BASH_ARGV[0]}"
+export MYLOCATION="${MYLOCATION%/*}"
+scriptDir=$MYLOCATION
+
+
+#echo "==============================================="
+#echo "Apple Installer Package Variables"
+#echo "*********************************"
+#echo "DEBUG: $ 1 = Full path to the installation package the installer app is processing: " $1
+#echo "DEBUG: $ 2 = Full path to the installation destination: " $2
+#echo "DEBUG: $ 3 = Installation volume (mountpoint) to receive the payload: " $3
+#echo "DEBUG: $ 4 = Root directory for the system: " $4
+#echo "DEBUG: Script Name: " $SCRIPT_NAME
+#echo "DEBUG: Package Path: " $PACKAGE_PATH
+#echo "DEBUG: Installer Temp: " $INSTALLER_TEMP
+#echo "DEBUG: Full path to the temp directory containing the operation executable: " $RECEIPT_PATH
+#echo "-----------------------------------------------"
+#echo ""
+
+
+
+# Initialise Script Globals
+
+stage0Loader="boot0"
+stage0LoaderDualBoot="boot0md"
+stage1LoaderHFS="boot1h"
+stage1LoaderFAT="boot1f32"
+stage2Loader="boot"
+
+targetVolume=$3
+targetDevice=$( df "${targetVolume}" | sed -n '2p' | awk '{print $1}' )
+targetDeviceRaw=${targetDevice/disk/rdisk}
+targetDisk=${targetDevice%s*}
+targetDiskRaw=${targetDisk/disk/rdisk}
+targetSlice=${targetDevice#*disk*s}
+
+targetResources="${targetVolume}/usr/local/bin/"
+
 echo "==============================================="
-echo "Diskmicrocodetype:"
-echo "******************"
+echo "DEBUG: display script variables"
+echo "*******************************"
 
-diskmicrocode=$( dd 2>/dev/null if=${bootdisk} count=1 | dd 2>/dev/null count=1 bs=437 | perl -ne '@a=split"";for(@a){printf"%02x",ord}' )
-diskmicrocodetypecounter=0
-while [ ${diskmicrocodetypecounter} -lt ${#diskmicrocodetype[@]} ]; do
-        diskmicrocodetypecounter=$(( ${diskmicrocodetypecounter} + 1 ))
-        diskmicrocodetypeid=${diskmicrocodetype[${diskmicrocodetypecounter}]#*,}
-        if [ ! "${diskmicrocode}" = "${diskmicrocode/${diskmicrocodetypeid}/}" ]; then
-                echo "${diskmicrocodetype[${diskmicrocodetypecounter}]%,*} found."
-	else
-		echo "Didn't find a match for ${diskmicrocodetype[${diskmicrocodetypecounter}]%,*}"
-        fi
-done
+echo "DEBUG: stage0Loader: Disk loader is ${stage0Loader}"
+echo "DEBUG: stage0LoaderDualBoot: Disk loader is ${stage0LoaderDualBoot}"
+echo "DEBUG: stage1LoaderHFS: Partition loader is ${stage1LoaderHFS}"
+echo "DEBUG: stage1LoaderFat: Partition loader is ${stage1LoaderFAT}"
+echo "DEBUG: stage2Loader: Filesystem loader is ${stage2Loader}"
+echo "DEBUG: targetVolume: Volume is ${targetVolume}"
+echo "DEBUG: targetDevice: Volume device is ${targetDevice}"
+echo "DEBUG: targetDeviceRaw: Volume raw device is ${targetDeviceRaw}"
+echo "DEBUG: targetDisk: Disk device is ${targetDisk}"
+echo "DEBUG: targetDiskRaw: Disk raw device is ${targetDiskRaw}"
+echo "DEBUG: targetSlice: Volume slice is ${targetSlice}"
+echo "DEBUG: targetResources: Boot Resources is ${targetResources}"
 echo "-----------------------------------------------"
 echo ""
-echo ""
-}
 
 
+# Write some information to the Install Log
+versionNumber=`cat "${scriptDir}"/Resources/version`
+revisionNumber=`cat "${scriptDir}"/Resources/revision`
+"$scriptDir"InstallLog.sh "${targetVolume}" "Installer version: ${versionNumber} ${revisionNumber}"
+"$scriptDir"InstallLog.sh "${targetVolume}" "Running Standard postinstall script
+Target volume = ${targetVolume}"
 
-checkdiskmicrocode ()
-{
-echo "==============================================="
-echo "Diskmicrocode:"
-echo "*************"
 
-# Note: The checks for Boot0 and Boot0hfs assume the code doesn't change!!
+# Double check we can see the selected partition and it's of the right type
+# if not the following script returns to indicate failure.
 
-# 1 action ( check or set )
+"$scriptDir"CheckProceed.sh "${targetVolume}" "${targetDevice}" "${targetVolume}" "${scriptDir}"
+returnValue=$?
+if [ ${returnValue}=0 ]; then
+	# OK to proceed
 
-diskmicrocode=$( dd 2>/dev/null if=${bootdisk} count=1 | dd 2>/dev/null count=1 bs=437 | perl -ne '@a=split"";for(@a){printf"%02x",ord}' )
-diskmicrocodemd5=$( dd 2>/dev/null if=${bootdisk} count=1 | dd 2>/dev/null count=1 bs=437 | md5 )
 
-#echo "${diskmicrocode}"
+	# Does a GRUB or Linux loader already exist in the disk's MBR?
+	# The script returns 1 if yes, 0 if no.
 
-if [ $( echo "${diskmicrocode}" | awk -F0 '{print NF-1}' ) = 874 ]; then
-	echo "Diskmicrocode = 874 (Which means the first 437 bytes of the MBR Disk Sector is blank)"
-	if [ "${1}" = "set" ]; then
-		echo "No disk microcode found. Updating."
-		diskupdate=true
-		echo "diskupdate is now set to true."
-	else
-		echo "No disk microcode found."
-	fi
-else
-	# There is already something on the MBR 
-	if [ ${1} = set ]; then
+	"$scriptDir"CheckGRUBLinuxLoader.sh "${targetDisk}" "${targetVolume}" "${scriptDir}"
+	returnValue=$?
+	if [ ${returnValue} = 0 ]; then
+		# OK to proceed
 
-		# See if a Windows bootloader already exists
-		windowsloader=$( dd 2>/dev/null if=${bootdisk} count=4 bs=1 | xxd | awk '{print $2$3}' )
-		if [ "${windowsloader}" == "33c08ed0" ]  ; then
-			echo "Found existing Windows Boot Loader"
-			echo "Will replace loader with Boot0hfs"
-			diskupdate=true
-			echo "diskupdate is now set to true."
+
+		# check for a 4-byte Windows disk signature in the disk's MBR.
+		# the following script returns 1 if a Windows disk signature exists, and 0 if not.
+
+		"$scriptDir"CheckWindowsDiskSignature.sh "${targetDisk}" "${targetVolume}" "${scriptDir}"
+		diskSigCheck=$?
+
+
+		# check for existing bootloaders in the disk's MBR
+		# and find out if we can write the Chameleon boot files.
+		# the following script returns 0 if we can proceed
+		# with writing the boot files, and 1 for not.
+
+		"$scriptDir"CheckDiskMicrocode.sh "${targetDisk}" "${diskSigCheck}" "${targetVolume}" "${scriptDir}"
+		diskupdate=$?
+
+
+		# check the format of the selected partition.
+		# the following script returns 1 if HFS
+		# the following script returns 2 if MSDOS
+		# the following script returns 0 if nothing
+
+		"$scriptDir"CheckFormat.sh "${targetDevice}" "${targetVolume}" "${scriptDir}"
+		espformat=$?
+
+
+		# check the partition scheme used for the selected disk.
+		# the following script returns 1 if GPT
+		# the following script returns 2 if GPT/MBR
+		# the following script returns 3 if MBR
+		# the following script returns 0 if nothing
+
+		"$scriptDir"CheckPartitionScheme.sh "${targetDisk}" "${targetVolume}" "${scriptDir}"
+		partitionTable=$?
+		if [ ${partitionTable} = 3 ]; then
+			# If MBR partition scheme then check for FAT16 or FAT32
+
+			# the following script returns 1 if FAT16
+			# the following script returns 2 if FAT32
+			# the following script returns 0 if nothing
+
+			"$scriptDir"CheckFatType.sh "${targetDeviceRaw}" "${targetVolume}" "${scriptDir}"
+			fatType=$?
 		fi
 
-		# See if a Chameleon stage0 boot file already exists
-		stage0type=$( dd 2>/dev/null if=${bootdisk} count=3 bs=1 skip=105 | xxd | awk '{print $2$3}' )
-		if [ "${stage0type}" == "0b807c" ] || [ "${stage0type}" == "0a803c" ] ; then
+		if [ "${fatType}" = 1 ] && [ "${partitionTable}" = 3 ]; then
+			echo "ERROR: - Can't install to a device using FAT16"
+			# Write error to Chameleon_Error_Log file
+			"$scriptDir"InstallLog.sh "${targetVolume}" "FAIL: Cannot install to a device using FAT16"
+		else
+			# Continue if the selected device is not a FAT16 format device
 
-			echo "Found existing Chameleon Stage 0 Loader"
-			# if found Boot0HFS without a Windows installation set diskupdate to true
-			if [ "${stage0type}" == "0b807c" ] && [ "${disksignature}" == "00000000" ]; then
-				echo "Found existing Chameleon Boot0HFS without a Windows installation"
-				echo "Will replace loader with Boot0"
-				diskupdate=true
-				echo "diskupdate is now set to true."
+			# Append a line break to the installer log
+			"$scriptDir"InstallLog.sh "${targetVolume}" "Line Break"
+
+			if [ ${diskupdate} = "0" ]; then
+				# Write the stage 0 loader to the MBR
+				"$scriptDir"WriteChameleonStage0.sh "${diskSigCheck}" "${stage0Loader}" "${stage0LoaderDualBoot}" "${targetDisk}" "${targetResources}" "${targetVolume}" "${scriptDir}"
+			else
+				#echo "Diskupdate = false, so didn't write the stage 0 loader to the MBR."
+				"$scriptDir"InstallLog.sh "${targetVolume}" "Stage 0 loader not written to ${targetDisk}."
 			fi
 
-			# if found Boot0 with a Windows installation set diskupdate to true
-			if [ "${stage0type}" == "0a803c" ] && [ "${disksignature}" != "00000000" ]; then
-				echo "Found existing Chameleon Boot0 with a Windows installation"
-				echo "Will replace loader with Boot0hfs"
-				diskupdate=true
-				echo "diskupdate is now set to true."
-			fi
-		fi
+			# Write the stage 1 loader to the partition boot sector
+			"$scriptDir"WriteChameleonStage1.sh "${espformat}" "${stage1LoaderHFS}" "${stage1LoaderFAT}" "${3}" "${targetDeviceRaw}" "${targetVolume}" "${scriptDir}"
 
-		# If neither a Windows or Chameleon Boot Loader exists
-		if [ "${stage0type}" != "0b807c" ] && [ "${stage0type}" != "0a803c" ] && [ "${windowsloader}" != "33c08ed0" ]  ; then
-			test=$(echo "${diskmicrocode}" | awk -F0 '{print NF-1}' )
-			echo "Disk microcode found: ${test} - Preserving."
-			echo "diskupdate is left at false"
-		fi
-	else
-		test=$(echo "${diskmicrocode}" | awk -F0 '{print NF-1}' )
-		echo "Disk microcode found: ${test}"
-	fi
-	echo "Disk microcode MD5 is ${diskmicrocodemd5}"
-fi
-echo "-----------------------------------------------"
-echo ""
-echo ""
-}
+			# Write the stage 2 loader to the root of the selected partition
+			"$scriptDir"WriteChameleonStage2.sh "${espformat}" "${stage2Loader}" "${3}" "${targetDevice}" "${targetVolume}" "${scriptDir}"
 
+			# Append a line break to the installer log
+			"$scriptDir"InstallLog.sh "${targetVolume}" "Line Break"
 
-checkdisksignature ()
-{
-echo "==============================================="
-echo "Find Disk Signature:"
-echo "*************"
-
-disksignature=$( dd 2>/dev/null if=${bootdisk} count=1 | dd 2>/dev/null count=4 bs=1 skip=440 | perl -ne '@a=split"";for(@a){printf"%02x",ord}' )
-
-echo "${disksignature}"
-
-if [ $disksignature = "00000000" ]; then
-	echo "Just Zero's found meaning Windows isn't installed."
-else
-	echo "Non Zero means we've found a Windows installation"
-fi
-echo "-----------------------------------------------"
-echo ""
-echo ""
-}
-
-
-
-checkpartitionbootcode ()
-{
-echo "==============================================="
-echo "Find Partition Bootcode:"
-echo "************************"
-
-# 1 action ( check or set )
-
-partitionbootcode=$( dd if=${bootrdev} count=1 2>/dev/null | perl -ne '@a=split"";for(@a){printf"%02x",ord}' )
-partitionbootcodeextended=$( dd if=${bootrdev} count=1 skip=1 2>/dev/null | perl -ne '@a=split"";for(@a){printf"%02x",ord}' )
-
-echo "${partitionbootcode}"
-
-if [ $( echo "${partitionbootcode}" | awk -F0 '{print NF-1}' ) = 1024 ]; then
-	echo "partitionbootcode = 1024 (Which means the whole 512 bytes of the MBR Disk Sector is blank)"
-	if [ "${1}" = "set" ]; then
-		echo "No partition bootcode found. Updating."
-	else
-		echo "No partition bootcode found."
-	fi
-else
-	if [ "${1}" = "set" ]; then
-		echo "Partition bootcode found. Overwriting."
-	else
-		echo "Partition bootcode found."
-	fi
-	if [ $( echo "${partitionbootcodeextended}" | awk -F0 '{print NF-1}' ) = 1024 ]; then
-		partitionbootcodemd5=$( dd 2>/dev/null if=${bootrdev} count=1 | md5 )
-	else
-		partitionbootcodemd5=$( dd 2>/dev/null if=${bootrdev} count=2 | md5 )
-		echo "Partition bootcode is dual sector."
-	fi
-	echo "Partition bootcode MD5 is ${partitionbootcodemd5}"
-fi
-
-echo "-----------------------------------------------"
-echo ""
-echo ""
-}
-
-
-start ${3}
-
-
-echo "==============================================="
-echo "Check the format of the selected partition"
-echo "*************************************"
-
-if [ "$( fstyp ${bootdev} | grep hfs )" ]; then
-	echo "${bootdev} is currently formatted as HFS"
-	efiformat="hfs"
-fi
-if [ "$( fstyp ${bootdev} | grep msdos )" ]; then
-	echo "${bootdev} is currently formatted as msdos"
-	efiformat="msdos"
-fi 
-echo "-----------------------------------------------"
-echo ""
-echo ""
-
-
-echo "==============================================="
-echo "Determine Partition Scheme:"
-echo "***************************"
-
-partitiontable=$( dd 2>/dev/null if=${bootdisk} count=1 skip=1 | dd 2>/dev/null count=8 bs=1 | perl -ne '@a=split"";for(@a){printf"%02x",ord}' )
-if [ "${partitiontable:0:16}" == "4546492050415254" ]; then	
-	partitiontable=$( dd 2>/dev/null if=${bootdisk} count=1 | dd 2>/dev/null count=64 bs=1 skip=446 | perl -ne '@a=split"";for(@a){printf"%02x",ord}' )
-	if [ "${partitiontable:8:2}" == "ee" ]; then
-		echo "Found System ID 'EE' to identify GPT Partition"
-		if [ "${partitiontable:40:2}" == "00" ] && [ "${partitiontable:72:2}" == "00" ] && [ "${partitiontable:104:2}" == "00" ]; then
-			echo "Found System ID '00' for each remaining possible partition"
-			partitiontable="GPT"
-	 	else
-			partitiontable="GPT/MBR"
+			# Set the active partition ONLY if Windows is not installed
+			"$scriptDir"SetActivePartition.sh "${espformat}" "${diskSigCheck}" "${targetDiskRaw}" "${targetSlice}" "${targetVolume}" "${scriptDir}"	
 		fi
 	fi
-else
-	partitiontable="MBR"
 fi
 
-echo "${partitiontable} found."
-echo "-----------------------------------------------"
-echo ""
-echo ""
-
-
-diskupdate=false
-
-
-checkdisksignature
-checkdiskmicrocodetype
-checkdiskmicrocode set
-checkpartitionbootcode set
-
-
+"$scriptDir"InstallLog.sh "${targetVolume}" "Line Break"
+"$scriptDir"InstallLog.sh "${targetVolume}" "Standard script complete"
 
 echo "==============================================="
-echo "Can we install the Chameleon bootloader files?"
-echo "**********************************************"
-
-if ${diskupdate}; then
-	echo "Diskupdate = true, so yes"
-	#---------------------------------------------------------------------
-	# Check bytes 438-446 of the GPTdiskProtectiveMBR for a Windows Disk Signature
-	# If there's no Windows disk signature then we can write boot0
-	#---------------------------------------------------------------------
-
-	if [ ${disksignature} == "00000000" ]; then
-		echo "Executing command: fdisk440 -u -f /usr/standalone/i386/${diskloader} -y ${bootdisk}"
-		"${bootresources}/Tools/fdisk440" -u -f "${bootvolume}/usr/standalone/i386/${diskloader}" -y ${bootdisk}
-	else
-		#---------------------------------------------------------------------
-		# If it exists then Windows is also installed on the HDD and we need to write boot0hfs
-		#---------------------------------------------------------------------
-		echo "Executing command: fdisk440 -u -f /usr/standalone/i386/${diskloaderdualboot} -y ${bootdisk}"
-		"${bootresources}/Tools/fdisk440" -u -f "${bootvolume}/usr/standalone/i386/${diskloaderdualboot}" -y ${bootdisk}
-	fi
-else
-echo "Diskupdate is false, so no stage 0 file was written"
-fi
-
-if [ ${efiformat} = "hfs" ]; then
-	echo "Executing command: dd if=/usr/standalone/i386/${partitionloaderhfs} of=${bootrdev}"
-	dd if="${bootvolume}/usr/standalone/i386/${partitionloaderhfs}" of=${bootrdev}
-fi
-
-if [ ${efiformat} = "msdos" ]; then
-	echo "Executing command: dd if=/usr/standalone/i386/${partitionloaderfat} of=${bootrdev}"
-	dd if="${bootvolume}/usr/standalone/i386/${partitionloaderfat}" of=${bootrdev}
-fi
-
-echo "Executing command: cp /usr/standalone/i386/${filesystemloader} ${bootvolume}"
-cp "${bootvolume}/usr/standalone/i386/${filesystemloader}" "${bootvolume}"
-
-echo "Executing command: ${bootresources}/Tools/SetFile -a V ${bootvolume}/${filesystemloader}"
-"${bootresources}/Tools/SetFile" -a V "${bootvolume}/${filesystemloader}"
-
+echo "END - Standard Post-Install Script"
+echo "*********************************"
 echo "-----------------------------------------------"
 echo ""
-echo ""
 
-
-echo "==============================================="
-echo "Set Active Partition ONLY if Windows is not installed"
-echo "*****************************************************"
-
-if [ ${disksignature} == "00000000" ]; then
-	# echo "Windows is not installed so let's change the active partition"
-
-	partitionactive=$( "${bootresources}/Tools/fdisk440" -d ${bootrdisk} | grep -n "*" | awk -F: '{print $1}')
-	echo "Current Active Partition: ${partitionactive}"
-
-	if [ "${partitionactive}" = "${bootslice}" ]; then
-		echo "${bootvolume} is already flagged as active"
-	else
-		echo "${bootvolume} is not flagged as active, so let's do it."
-		# BadAxe requires EFI partition to be flagged active.
-		# but it doesn't' hurt to do it for any non-windows partition.
-		
-		"${bootresources}/Tools/fdisk440" -e ${bootrdisk} <<-MAKEACTIVE
-		print
-		flag ${bootslice}
-		write
-		y
-		quit
-		MAKEACTIVE
-	fi
-else
-	echo "Windows is installed so we let that remain the active partition"
-fi
-echo "-----------------------------------------------"
-echo ""
-echo ""
-
-# hide boot file
-chflags hidden "${3}/boot"
-echo "boot file hidden ${3}/boot"
-
-exit
+exit 0
