Update Chameleon pkg Installer (Allow install on ESP). (Credits to Micky1979)

diff --git a/Enoch/package/Scripts.templates/InstallTheme/postinstall b/Enoch/package/Scripts.templates/InstallTheme/postinstall
--- a/Enoch/package/Scripts.templates/InstallTheme/postinstall
+++ b/Enoch/package/Scripts.templates/InstallTheme/postinstall
@@ -2,21 +2,35 @@
 
 set -u
 
-targetVolume="$3"
+configFile='/private/tmp/InstallConfig.plist'
+v_mntptDev=$( /usr/libexec/PlistBuddy -c "Print :ramdisk" ${configFile} | sed -e 's/[[:blank:]]*//g' )
+v_mntpt=$( LC_ALL=C diskutil info ${v_mntptDev} | grep -i 'mount point' | awk '{$1=$2=""; print $0}' \
+                                                                                | sed -e 's/^[ \t]*//' )
 
 themeName="@themeName@"
 themeDir="@themeDir@"
 logName="@LOG_FILENAME@"
-logFile="${targetVolume}/$logName"
 
 # Check if target volume exists
-if [[ ! -d "$targetVolume" ]]; then
-    echo "$targetVolume volume does not exist!" >&2
+if [[ ! -d "${v_mntpt}" ]]; then
+    echo "$v_mntpt volume does not exist!" >&2
     exit 1
 fi
 
-exec >>"${logFile}" 2>&1
+mainLine="=============================================================================="
+subLine="------------------------------------------------------------------------------"
 
-[[ -d "${targetVolume}/Extra/Themes/$themeDir" ]] && echo "Theme $themeName installed"
+exec > >(tee -a "${v_mntpt}/${logName}") 2>&1
 
+echo "$mainLine"
+echo "Installing Theme $themeName"
+echo "$subLine"
+
+if [[ -d  "${v_mntpt}/Extra/Themes/$themeDir" ]]; then
+    echo "Theme $themeName installed"
+else
+    echo "*** ERROR:$themeName not installed"
+fi
+
+echo "$subLine"
 exit 0
diff --git a/Enoch/package/Scripts.templates/Pre/preinstall b/Enoch/package/Scripts.templates/Pre/preinstall
--- a/Enoch/package/Scripts.templates/Pre/preinstall
+++ b/Enoch/package/Scripts.templates/Pre/preinstall
@@ -1,30 +1,15 @@
 #!/bin/bash
 
-echo "==============================================="
-echo "Pre-Install Script"
-echo "*********************************"
-echo "-----------------------------------------------"
-echo ""
-
 # Creates text file named '@LOG_FILENAME@'
 # at the root of the target volume. This is to give the user
 # a record of the installation process and also to show why
 # possibly the installation process failed (even though the
 # package installer ends reading 'Installation Successful').
 
-# This script also prepares, then backs up any previous
-# stage2 boot file, /Extra folder and install log if they exist.
+# This script also prepares the Ram Disk and the InstallConfig.plist
+mainLine="=============================================================================="
+subLine="------------------------------------------------------------------------------"
 
-# Find location of this script in the package installer
-# so we know where all the other scripts are located.
-
-MYLOCATION="${PWD}/${BASH_ARGV[0]}"
-export MYLOCATION="${MYLOCATION%/*}"
-scriptDir=$MYLOCATION
-
-
-# If target volume root of current system then replace
-# / with volume name.
 if [ "$3" == "/" ]
 then
     targetVolume="/Volumes/"$( ls -1F /Volumes | sed -n 's:@$::p' )
@@ -32,68 +17,75 @@ else
     targetVolume="$3"
 fi
 
+v_mntpt="/Volumes/BOOTRAMDISK"
+size='409600' # is the size of a standard EFI partition
 logName="@LOG_FILENAME@"
-logFile="${targetVolume}/$logName"
+configFile="/private/tmp/InstallConfig.plist"
 
-# ---------------------------------------------
+# Functions to create/umount the RAM DISK
+UMOUNT_VDISK() {
+        umount -f "${1}"
+        hdiutil detach "${1}"
+}
+
+RAM_DISK() {
+    if [ $( df | awk '{$1=$2=$3=$4=$5=$6=$7=$8=""; print $0}' | sed -e 's/^[ \t]*//' | \
+                                                                grep -x "${v_mntpt}" ) ]; then
+        devToUmount=$( LC_ALL=C diskutil info "${v_mntpt}" | grep -i 'Device Node:' | awk '{print $3}' )
+        UMOUNT_VDISK $devToUmount
+    fi
+    echo "CREATING RAM DISK"
+#    mkdir -p $v_mntpt
+
+    dev=$(hdiutil attach -nomount ram://${size})
+    if [ $? -eq 0 ] ; then
+        diskutil erasevolume FAT32 "BOOTRAMDISK" ${dev}
+    else
+        echo "Failed to create the Ram Disk, installation aborted!"
+        exit 1
+    fi
+
+    rm -f $configFile
+    # adding the Ram disk device to InstallConfig.plist to be shared with other packages
+    /usr/libexec/PlistBuddy -c "Add :ramdisk  string ${dev}" $configFile
+}
+
+RAM_DISK
+
+# ensure that ram disk has "/Volumes/BOOTRAMDISK" mount point
+v_mntpt=$( LC_ALL=C diskutil info ${dev} | grep -i 'mount point' | awk '{$1=$2=""; print $0}' \
+                                                                               | sed -e 's/^[ \t]*//' )
+if [ ! -d "${v_mntpt}" ]; then
+    echo "Ram Disk not found!"
+    exit
+fi
+
+touch "${v_mntpt}/${logName}"
+exec > >(tee -a "${v_mntpt}/${logName}") 2>&1
+
+echo "$mainLine"
+echo "Pre-Install Script"
+echo "$subLine"
+
+# creating a symlink (from Clover)
+echo "Creating ${targetVolume}/EXTRAROOTDIR symlink targeting ${v_mntpt}"
+ln -sf "${v_mntpt}" "${targetVolume}/EXTRAROOTDIR"
+
 # Preparing Backing up of Chameleon files
-# ---------------------------------------------
 backupRootDir="${targetVolume}/Chameleon.Backups"
-backupDir="${backupRootDir}/"$( date -j "+%F-%Hh%M" )
+backupDir=$( date -j "+%F-%Hh%M" )
 
 # Create the backup directory
-mkdir -p "$backupDir"
+mkdir -p "${backupRootDir}/${backupDir}"
 
-[[ -f "$logFile" ]] && mv "$logFile" "${backupDir}/${logName}" # Backup old log file
+# Remove the invisible flag of files in the backups
+chflags -R nohidden "${backupRootDir}"
 
-# Setup Chameleon Log file
-# by writing header and diskutil list
+# adding the backupdir name to InstallConfig.plist to be shared with other packages
+/usr/libexec/PlistBuddy -c "Add :backupDir  string ${backupDir}" $configFile >/dev/null
 
-echo "Chameleon installer log - $( date )
-Installer version: %CHAMELEONVERSION% %CHAMELEONREVISION%
-======================================================" >"${logFile}"
-
-diskutil list >>"${logFile}"
-echo "======================================================" >>"${logFile}"
-
-# ---------------------------------------------
-# Backup Chameleon files
-# ---------------------------------------------
-echo "Backup Chameleon files" >>"${logFile}"
-# Backup stage2
-if [[ -f "${targetVolume}/boot" ]];then
-    echo "Backup stage2 file ${targetVolume}/boot to ${backupDir}/boot" >>"${logFile}"
-    cp -p "${targetVolume}/boot" "${backupDir}/boot"
-fi
-# Backup /Extra directory
-if [[ -d "${targetVolume}/Extra" ]];then
-    echo "Backing up ${targetVolume}/Extra folder to ${backupDir}/Extra" >>"${logFile}"
-    cp -pR "${targetVolume}/Extra" "${backupDir}/Extra"
-fi
-
-chflags -R nohidden "$backupDir" # Remove the invisible flag of files in the backups
-
-find "${backupRootDir}" -type d -depth -empty -exec rmdir {} \; # Remove empty directories
-
-echo "======================================================" >>"${logFile}"
-
-# Check existing plist name for old naming convention and change to new convention.
-if [[ -f "${targetVolume}/Extra/com.apple.Boot.plist" ]]; then
-  echo "Renaming existing com.apple.Boot.plist to org.chameleon.Boot.plist" >>"${logFile}"
-  mv "${targetVolume}/Extra/com.apple.Boot.plist" "${targetVolume}/Extra/org.chameleon.Boot.plist"
-fi
-
-# ---------------------------------------------
-# Clearing options that Chameleon can managed
-# ---------------------------------------------
-echo "Clearing options..." >>"${logFile}"
-"${PWD}/clean_bootplist.pl" "${targetVolume}" 2>&1 | grep -v 'Does Not Exist' >>"${logFile}"
-echo "======================================================" >>"${logFile}"
-
-echo "==============================================="
+diskutil list >> "${v_mntpt}/${logName}"
+echo "$subLine"
 echo "END - Pre-Install Script"
-echo "*********************************"
-echo "-----------------------------------------------"
-echo ""
 
 exit 0
